algoritmo "exemplo 1"
// Função :
// Autor :
// Data : 07/10/2014
// Seção de Declarações
var
matricula:inteiro
media:real
situacao:caractere
inicio
Escreva("Digite asua matricula: ")
Leia(matricula)
Escreva("digite a sua media ")
Leia(media)
Escreva("digite a sua situacao")
Leia(situacao)


Escreval("Sua matricula e ",matricula)
Escreval("Sua media foi ",media)
Escreva("Sua situacao foi",situacao)



fimalgoritmo
